#!/usr/bin/env ruby
require 'sinatra'
require 'yaml'
require_relative 'api'

token = YAML.load_file('secret.yml')['api_token']
kollus = Kollus.new 'test', 'catenoid-sample', token

media_token1 = kollus.media '7MscjbVl'
media_token2 = kollus.media 'Kcrbjc2S'

get '/' do
  foo = 'asdf'
  erb :index, locals: {
    media_token1: media_token1,
    media_token2: media_token2
  }
end
