#!/usr/bin/env ruby
require 'yaml'
require_relative 'api'

api_token = YAML.load_file('secret.yml')['api_token']
account_id = 'test'
account_key = 'catenoid-sample'

media_token1 = media_link(api_token, account_id, account_key, '7MscjbVl')
media_token2 = media_link(api_token, account_id, account_key, 'Kcrbjc2S')

puts media_token1
puts media_token2
