#!/usr/bin/env ruby
require 'sinatra'
require 'yaml'
require 'tilt/erubis'
require_relative '../lib/kollus'

path_secret = File.join File.dirname(__FILE__), 'secret.yml'
token = YAML.load_file(path_secret)['api_token']

kollus = Kollus.new 'test', 'catenoid-sample', token

get '/' do
  @media1 = kollus.media '7MscjbVl'
  @media2 = kollus.media 'Kcrbjc2S'
  @upload = kollus.upload

  erb :index
end
