#!/usr/bin/env ruby
require 'sinatra'
require 'yaml'
require_relative '../lib/kollus'

token = YAML.load_file('secret.yml')['api_token']
kollus = Kollus.new 'test', 'catenoid-sample', token

get '/' do
  @upload_uri = kollus.upload_uri
  @media_token1 = kollus.media '7MscjbVl'
  @media_token2 = kollus.media 'Kcrbjc2S'

  erb :index
end
